'------------------------------------------------------------------------------
' <auto-generated>
'     Archivo generado para mantener compatibilidad con el proyecto WebForms.
' </auto-generated>
'------------------------------------------------------------------------------
Option Strict On
Option Explicit On

Partial Public Class listas_pld
End Class
