'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class CambiarPassword
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    Protected WithEvents litMensaje As Global.System.Web.UI.WebControls.Literal
    Protected WithEvents txtActual As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtNueva As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents txtConfirmar As Global.System.Web.UI.WebControls.TextBox
    Protected WithEvents btnGuardar As Global.System.Web.UI.WebControls.Button
End Class
